# Generated by Django 3.2.4 on 2021-06-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candlesticks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candlestick',
            name='symbol',
            field=models.CharField(choices=[('EURUSD', 'EURUSD'), ('EURGBP', 'EURGBP'), ('EURAUD', 'EURAUD'), ('EURCAD', 'EURCAD'), ('EURCHF', 'EURCHF'), ('EURJPY', 'EURJPY'), ('EURNZD', 'EURNZD'), ('AUDCAD', 'AUDCAD'), ('AUDCHF', 'AUDCHF'), ('AUDJPY', 'AUDJPY'), ('AUDNZD', 'AUDNZD'), ('AUDUSD', 'AUDUSD'), ('CADCHF', 'CADCHF'), ('CADJPY', 'CADJPY'), ('CHFJPY', 'CHFJPY'), ('GBPAUD', 'GBPAUD'), ('GBPCAD', 'GBPCAD'), ('GBPCHF', 'GBPCHF'), ('GBPJPY', 'GBPJPY'), ('GBPNZD', 'GBPNZD'), ('GBPUSD', 'GBPUSD'), ('NZDCAD', 'NZDCAD'), ('NZDCHF', 'NZDCHF'), ('NZDJPY', 'NZDJPY'), ('NZDUSD', 'NZDUSD'), ('USDCAD', 'USDCAD'), ('USDCHF', 'USDCHF'), ('USDJPY', 'USDJPY')], default='EURUSD', max_length=6, verbose_name='Symbol'),
        ),
    ]
