# Generated by Django 3.2.4 on 2021-06-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candlesticks', '0004_auto_20210627_2318'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='candlestick',
            name='one_candlestick_per_timeframe_per_source',
        ),
        migrations.AddField(
            model_name='candlestick',
            name='price_type',
            field=models.CharField(choices=[('BID', 'Bid'), ('ASK', 'Ask')], default='BID', max_length=3, verbose_name='Price type'),
        ),
        migrations.AlterField(
            model_name='candlestick',
            name='source',
            field=models.CharField(choices=[('Dukascopy', 'Dukascopy'), ('Pandas', 'Pandas')], default='Pandas', max_length=16, verbose_name='Source'),
        ),
        migrations.AddConstraint(
            model_name='candlestick',
            constraint=models.UniqueConstraint(fields=('symbol', 'time', 'period', 'price_type', 'source'), name='one_candlestick_per_timeframe_per_source'),
        ),
    ]
