# Generated by Django 3.2.4 on 2021-07-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candlesticks', '0006_alter_candlestick_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candlestick',
            name='time',
            field=models.DateTimeField(verbose_name='Datetime'),
        ),
    ]
