# Generated by Django 3.2.4 on 2021-07-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candlesticks', '0008_alter_candlestick_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candlestick',
            name='symbol',
            field=models.CharField(choices=[('EURUSD', 'EURUSD'), ('USDJPY', 'USDJPY'), ('GBPUSD', 'GBPUSD'), ('AUDUSD', 'AUDUSD'), ('USDCAD', 'USDCAD'), ('USDCHF', 'USDCHF'), ('NZDUSD', 'NZDUSD'), ('EURJPY', 'EURJPY'), ('AUDCAD', 'AUDCAD'), ('AUDCHF', 'AUDCHF'), ('AUDJPY', 'AUDJPY'), ('AUDNZD', 'AUDNZD'), ('CADCHF', 'CADCHF'), ('CADJPY', 'CADJPY'), ('CHFJPY', 'CHFJPY'), ('EURAUD', 'EURAUD'), ('EURCAD', 'EURCAD'), ('EURCHF', 'EURCHF'), ('EURGBP', 'EURGBP'), ('EURNZD', 'EURNZD'), ('GBPAUD', 'GBPAUD'), ('GBPCAD', 'GBPCAD'), ('GBPCHF', 'GBPCHF'), ('GBPJPY', 'GBPJPY'), ('GBPNZD', 'GBPNZD'), ('NZDCAD', 'NZDCAD'), ('NZDCHF', 'NZDCHF'), ('NZDJPY', 'NZDJPY')], default='EURUSD', max_length=6, verbose_name='Symbol'),
        ),
    ]
