# Generated by Django 3.2.4 on 2021-06-11 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=7, verbose_name='Symbol')),
            ],
        ),
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Time')),
                ('open', models.FloatField(verbose_name='Open')),
                ('high', models.FloatField(verbose_name='High')),
                ('low', models.FloatField(verbose_name='Low')),
                ('close', models.FloatField(verbose_name='Close')),
                ('volume', models.FloatField(verbose_name='Volume')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bars.symbol')),
            ],
        ),
    ]
