# Generated by Django 3.2.4 on 2021-06-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candlestick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=12, verbose_name='Symbol')),
                ('time', models.DateTimeField(unique=True, verbose_name='Datetime')),
                ('open', models.FloatField(verbose_name='Open')),
                ('high', models.FloatField(verbose_name='High')),
                ('low', models.FloatField(verbose_name='Low')),
                ('close', models.FloatField(verbose_name='Close')),
                ('volume', models.FloatField(verbose_name='Volume')),
                ('period', models.IntegerField(choices=[(0, 'Tick'), (1, 'M1'), (5, 'M5'), (15, 'M15'), (30, 'M30'), (60, 'H1'), (240, 'H4'), (1440, 'D1'), (10080, 'W1'), (43200, 'MN')], default=0, verbose_name='Period')),
            ],
        ),
        migrations.AddConstraint(
            model_name='candlestick',
            constraint=models.UniqueConstraint(fields=('symbol', 'time', 'period'), name='one_candlestick_per_timeframe'),
        ),
    ]
