# Generated by Django 3.2.4 on 2021-07-31 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candlesticks', '0009_alter_candlestick_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candlestick',
            name='symbol',
            field=models.CharField(choices=[('EURUSD', 'EURUSD'), ('USDJPY', 'USDJPY'), ('GBPUSD', 'GBPUSD'), ('AUDUSD', 'AUDUSD'), ('USDCAD', 'USDCAD'), ('USDCHF', 'USDCHF'), ('NZDUSD', 'NZDUSD'), ('EURJPY', 'EURJPY'), ('GBPJPY', 'GBPJPY'), ('EURGBP', 'EURGBP'), ('AUDJPY', 'AUDJPY'), ('EURAUD', 'EURAUD'), ('EURCHF', 'EURCHF'), ('AUDNZD', 'AUDNZD'), ('NZDJPY', 'NZDJPY'), ('GBPAUD', 'GBPAUD'), ('GBPCAD', 'GBPCAD'), ('EURNZD', 'EURNZD'), ('AUDCAD', 'AUDCAD'), ('GBPCHF', 'GBPCHF'), ('AUDCHF', 'AUDCHF'), ('EURCAD', 'EURCAD'), ('CADJPY', 'CADJPY'), ('GBPNZD', 'GBPNZD'), ('CADCHF', 'CADCHF'), ('CHFJPY', 'CHFJPY'), ('NZDCAD', 'NZDCAD'), ('NZDCHF', 'NZDCHF')], default='EURUSD', max_length=6, verbose_name='Symbol'),
        ),
    ]
