# Generated by Django 4.0.4 on 2022-05-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candlesticks', '0010_alter_candlestick_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='candlestick',
            name='predicted_close',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Predicted Close'),
        ),
        migrations.AddField(
            model_name='candlestick',
            name='predicted_high',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Predicted High'),
        ),
        migrations.AddField(
            model_name='candlestick',
            name='predicted_low',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Predicted Low'),
        ),
        migrations.AddField(
            model_name='candlestick',
            name='predicted_open',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Predicted Open'),
        ),
    ]
