# Generated by Django 4.0.4 on 2022-05-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candlesticks', '0011_candlestick_predicted_close_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candlestick',
            name='predicted_volume',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Predicted Volume (M)'),
        ),
        migrations.AlterField(
            model_name='candlestick',
            name='close',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Close'),
        ),
        migrations.AlterField(
            model_name='candlestick',
            name='high',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='High'),
        ),
        migrations.AlterField(
            model_name='candlestick',
            name='low',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Low'),
        ),
        migrations.AlterField(
            model_name='candlestick',
            name='open',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Open'),
        ),
        migrations.AlterField(
            model_name='candlestick',
            name='source',
            field=models.CharField(choices=[('Dukascopy', 'Dukascopy'), ('Pandas', 'Pandas')], default='Dukascopy', max_length=16, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='candlestick',
            name='volume',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Volume (M)'),
        ),
    ]
